name: Build Project
description: 'Builds the project using Turborepo in a monorepo setup'
defaults:
  run:
    working-directory: ./monorepo
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build the monorepo project

    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup-environment.yml

      - name: Build project
        run: pnpm turbo run build --cache-dir=.turbo