name: Build Project
defaults:
  run:
    working-directory: ./monorepo
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build the monorepo project

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Build project
        run: pnpm turbo run build --cache-dir=.turbo

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        working-directory: ./monorepo/apps/web
        with:
          name: web-artifact
          path: |
            dist
            .next
            .turbo
            node_modules
            public