name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  typecheck:
    uses: ./.github/workflows/typecheck.yml

  test:
    uses: ./.github/workflows/test.yml
    needs: [typecheck]

  build:
    uses: ./.github/workflows/build.yml
    needs: [test]
