name: CI Pipeline

on:
  push:
    branches: [feature/*, feature/**/*]
  pull_request:
    branches: [develop, main]

defaults:
  run:
    working-directory: ./monorepo

jobs:
   run-tests:
    runs-on: ubuntu-latest
    name: Run tests in monorepo

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Run tests
        run: pnpm turbo run test  --cache-dir=.turbo
   
   build-api:
    runs-on: ubuntu-latest
    needs: run-tests
    name: Build api project (adonisjs)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Build project
        run: pnpm run build --filter api --cache-dir=.turbo
            
   build-web:
    runs-on: ubuntu-latest
    needs: run-tests
    name: Build web project (nextjs)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Build project
        run: pnpm run build --filter web --cache-dir=.turbo

   