name: Docker Build and Push

on:
  workflow_call:

defaults:
  run:
    working-directory: ./monorepo

jobs:
  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./monorepo/dist/

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t my-typescript-app .
        working-directory: ./monorepo

      - name: Push Docker image
        run: docker push my-typescript-app
