name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./monorepo

jobs:
  call-test-workflow:
    uses: ./.github/workflows/test.yml

  call-build-workflow:
    needs: call-test-workflow
    uses: ./.github/workflows/build.yml

  call-containerize-workflow:
    needs: call-containerize-workflow
    uses: ./.github/workflows/containerize.yml
