name: Tubro Run Tests
on:
  workflow_call:

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Configure pnpm store directory
        run: pnpm config set store-dir .pnpm-store

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: .pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install
        working-directory: ./monorepo