name: Tubro Run Tests

on:
  workflow_call:

name: Turborepo Run Tests
on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
        working-directory: ./monorepo

      - name: Run tests
        run: pnpm test
        working-directory: ./monorepo
