name: Tests running by Turborepo
description: 'Runs tests using Turborepo in a monorepo setup'
defaults:
  run:
    working-directory: ./monorepo
on:
  workflow_call:
jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run tests in monorepo

    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup-environment.yml

      - name: Run tests
        run: pnpm turbo run test  --cache-dir=.turbo