name: Tubro Run Tests

on:
  workflow_call:

defaults:
  run:
    working-directory: ./monorepo

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files
        run: ls -la

      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm test

      - name: Install dependencies
        run: pnpm install

      - name: Restore Turborepo cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Run tests
        run: pnpm run test
