name: Tubro Run Tests

on:
  workflow_call:
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Cache pnpm store and node_modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            monorepo/node_modules
            monorepo/apps/api/node_modules
            monorepo/apps/web/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('monorepo/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Cache Turborepo
        uses: actions/cache@v4
        with:
          path: monorepo/.turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: |
          cd monorepo
          pnpm install

      - name: Build (with Turborepo)
        run: |
          cd monorepo
          pnpm turbo run build --cache-dir=.turbo

      - name: Run tests with coverage
        run: |
          cd monorepo/apps/api
          pnpm run test:coverage

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
